### ISSUE TITLE
Error adding ng-momentum

### ISSUE THREAD

**Issue by jimmytea** [BottleRocketStudios/ng-momentum#2]
Created a new Angular project and ran `ng add ng-momentum`. This resulted in the following error messaging:

Installing packages for tooling via npm.
\+ ng-momentum@0.0.15
added 28 packages from 362 contributors and audited 40411 packages in 11.189s
Installed packages for tooling via npm.
    rootPath Path: 
    Source Path: src
    appPath: src/app
    options.path: /src
**Cannot read property 'entries' of undefined**

I'm also seeing this error if I subsequently run `ng g ng-momentum:scaffold --spec=false --force`

My environment:
Angular CLI: 6.1.4
Node: 8.11.1
OS: darwin x64
Angular: 6.1.3

**Comment by jonbcampos** [comment]
@jimmytea I'm seeing this as an issue that is also showing up in the angular-cli repo.

**Comment by jimmytea** [comment]
@jonbcampos dropping back to CLI 6.0.7 did the trick! Thanks.
