### ISSUE TITLE
Generated code breaking the default VS Code TypeScript linter

### ISSUE THREAD

**Issue by jimmytea** [BottleRocketStudios/ng-momentum#3]
I've run the scaffold command and created a new view and it causes TS Lint (https://marketplace.visualstudio.com/items?itemName=eg2.tslint) in VS Code to throw errors in a number of places under the default linter settings. Bear in mind, this does **not** cause any build issues, just linter errors that have to be cleaned up. I'll list them out here.

After generating a new form view the following errors were present:
**/src/app/services/<service>/<service>.service.spec.ts**
- Various it() definitions are invalidating the > 140 characters long rule.
- The describe() blocks are all set in one tab too far 

**/src/app/services/<service>/<service>.service.ts**
- Various instances of violating the trailing white-space rule
- Various instances of missing white-space between characters (e.g. if(){})

**/src/app/views/<service>/<service>.component.spec.ts**
- The imports list has weird line breaks where there shouldn't be any

**/src/app/views/<service>/<service>.component.ts**
- Various instances of violating the trailing whitespace rule, particularly because the ngInit function has a bunch of newlines for some reason. Other places just have extra spaces that shouldn't be there.

**/src/app/views/<service>/<service>.module.ts**
- the import for the Angular Material package is using double-quotes when it should be using single-quotes
- The imports list has weird line breaks where there shouldn't be any

**/src/app/views/<service>/<service>.routing.module.ts**
- Missing EOF newline

**/src/app/vos/<service>/<service>.spec.ts**
- Missing EOF newline

**/src/app/vos/<service>/<service>.ts**
- Various instances of trailing whitespace
- Missing EOF newline
- The sample VO named 'id' is of type number (correct) but the linter is complaining that the type is easily inferred because the value of id is numeric. Not sure what could be done here other than not giving it a numeric default value.

**/src/app/app.routing.module.ts**
- The generated route uses strings for both the keys (stylistic choice but not how I personally do it, still fine though) and the values in the generated route object. The strings are using double-quotes when they should be single-quotes.

That's it, other than the above everything generated correctly!

**Comment by jonbcampos** [comment]
@jimmytea looking into it now
