### ISSUE TITLE
Unlisted dependency on @angular/service-worker

### ISSUE THREAD

**Issue by jimmytea** [BottleRocketStudios/ng-momentum#5]
Adding ng-momentum to a project adds a @angular/service-worker dependency to app.module.ts but service worker is not added correctly. The Getting Started docs suggest adding @angular/pwa if you 'want to include PWA features' but it appears the base project also has a dependency on service worker (something that adding @angular/pwa provides).

**Comment by jonbcampos** [comment]
@jimmytea made it based on the `includePwa` parameter. closing. #
